version: '3'

services:
  tests:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpunit --filter=PngEncoderTest"
    volumes:
      - ./:/project
  coverage:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpunit --coverage-text"
    volumes:
      - ./:/project
    environment:
      - XDEBUG_MODE=coverage
  analysis:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpstan analyze --memory-limit=512M ./src"
    volumes:
      - ./:/project
  standards:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpcs"
    volumes:
      - ./:/project
