services:
  tests:
    build: ./
    working_dir: /project
    entrypoint: ["./vendor/bin/phpunit"]
    volumes:
      - ./:/project
  coverage:
    build: ./
    working_dir: /project
    entrypoint: ["./vendor/bin/phpunit", "--coverage-text"]
    volumes:
      - ./:/project
    environment:
      - XDEBUG_MODE=coverage
  analysis:
    build: ./
    working_dir: /project
    entrypoint: ["./vendor/bin/phpstan", "analyze", "--memory-limit=512M"]
    volumes:
      - ./:/project
  standards:
    build: ./
    working_dir: /project
    entrypoint: ["./vendor/bin/phpcs"]
    volumes:
      - ./:/project
