version: '3'

services: 
  tests:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpunit -vvv"
    volumes:
      - ./:/project
  analysis:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpstan analyze --level=4 ./src"
    volumes:
      - ./:/project
