name: Tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0']
    name: Testing on PHP ${{ matrix.php-versions }}
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v2
      - name: 'Setup Environment'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: imagick,gd
          tools: phpunit,composer
      - name: 'Install Dependencies'
        run: composer install -o -q
      - name: 'Run PHPUnit'
        run: vendor/bin/phpunit